PassEnv database.default.hostname
PassEnv database.default.database
PassEnv database.default.username
PassEnv database.default.password
PassEnv database.default.DBDriver
PassEnv database.default.port
PassEnv app.baseURL
PassEnv CI_ENVIRONMENT